name: pet_home
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  formz: ^0.8.0
  auto_route: ^10.1.0+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
  - assets/images/app_logo.jpg
  - assets/icons/apple-logo.png
  - assets/icons/google.png
  - assets/images/vector.png
  - assets/icons/house_icon.png
  - assets/icons/heart_icon.png
  - assets/icons/person_icon.png
  - assets/icons/settings_icon.png
  - assets/icons/search_icon.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700